infotech-class-3/class-3-homeworks

2022-12-18/19-ÜMİTT/HOMEWORK.txt

hocam fazla kodu sildim. onaylar misin?

remove extra code.

---

2023-01-08/10-mehmetalp/css-HW-10-mehmetAlp.css
2023-01-08/10-mehmetalp/css-HW-10-mehmetAlp.html

10-MehmetAlp-css odev

---

2023-01-15/20-Y.Emre/index.html
2023-01-15/20-Y.Emre/readme.md

20-Y.Emre-bootsrap ödev

---

2023-01-15/16-Sena/README.md
2023-01-15/16-Sena/index.html

16-Sena-Bootstrap odev

---

2023-01-15/10-mehmetalp/odev-bootstrap.html

10-Mehmetalp - bootstrap odev

---

2023-01-15/01-Ahmet/index.html

Boostrap Odev Ahmet

---

2023-01-15/14-Neslihan bootstrap/index.html

bootstrap
degisiklikler yapildi

14-Neslihan-Bootstrap homework

---

2023-01-15/19-Ümit/index.html

Hocam ödev yeni bitti. Kusura bakmayın dün akşam için.

19-ümit homework

---

2023-01-15/15-Salih/bootstrap-odevi.html

15 salih bootstrap

---

2023-01-15/odevcözümü/index.html

m-fth - bootstrap_cocum

---

2023-01-15/06-Hasan/index.html

06-Hasan - bootstrap ödev

---

2023-01-15/07-H.Arif/index.html

css_Bootstrap_07-HArif

---

2023-01-22/05-Furkan/README.md
2023-01-22/05-Furkan/script.js

05-Furkan - JavaScript Odev

---

2023-01-22/16-Sena/script.js

16-Sena - javascript odev

---

2023-01-22/02-Ali/odev.js

02-Ali - JavaScript Hero 1-6 ödev

---

2023-01-22/14-Neslihan/script.js

14-Neslihan-JS

---

2023-01-22/20-Y.Emre/script.js

script ödevi

---

2023-01-22/01-Ahmet/odev5.html
2023-01-22/01-Ahmet/odev5.js

Ahmet js-1

---

2023-01-22/17-sila/sila.js

Add Sıla's homework

---

2023-01-22/18-Tuba Neda/homework-week-five.js

18-Tuba Neda-js ödev

---

2023-01-29/05-Furkan/README.md
2023-01-29/05-Furkan/index.html
2023-01-29/05-Furkan/script.js

05-Furkan - Basic Calculator Odev

---

2023-01-22/21-Yusuf/js-basics.js

21-Yusuf-js-basics-homework

---

2023-01-22/07-H.Arif/script_07-HArif.js

07-H_Arif-jscript

---

2023-01-29/20-Y.emre/README.md
2023-01-29/20-Y.emre/index.html
2023-01-29/20-Y.emre/ödev.js

20-y.emre javascriptödev 

---

2023-01-22/12-mustafa/index.html

12-mustafa

---

2023-01-29/07-H.Arif/index.html
2023-01-29/07-H.Arif/script.js

07-HArif-simpleCalculator

---

2023-01-29/19-Ümit/index.html
2023-01-29/19-Ümit/ödev.js

29.01.2023- 19-Ümit

---

2023-01-29/15-Salih/calculator.css
2023-01-29/15-Salih/calculator.html
2023-01-29/15-Salih/calculator.js

15 salih calculator

---

2023-01-29/14-Neslihan/calculator.js
2023-01-29/14-Neslihan/index.html

14-Neslihan

---

2023-01-29/09-Kenan/app.js
2023-01-29/09-Kenan/index.html

09-Kenan JS Homework

---

2023-01-22/09-Kenan/app.js
2023-01-22/09-Kenan/index.html

09-Kenan JS 22 Januar Homework

---

2023-01-29/21-Yusuf/calculator.js
2023-01-29/21-Yusuf/index.html

21-Yusuf-Calculator-Homework

---

2023-01-29/06-Hasan/index.html
2023-01-29/06-Hasan/secondWoche.js

06-Hasan - JS Hesap ödev

---

2023-02-05/odev.md

add 2023-02-05 odev

---

2023-01-29/cozum/hesap.js
2023-01-29/cozum/index.html

2023-01-29 hafta odev cozumleri

---

2023-01-29/18-TubaNeda/js/ödev.js

18-Neda: update homework

---

2023-02-05/21-Yusuf/app.js
2023-02-05/21-Yusuf/index.html

21-Yusuf-Array-methods-homework

---

2023-02-05/17-Sıla/index.html
2023-02-05/17-Sıla/index.js

17 silakizil

---

2023-02-05/14-Neslihan/index.html
2023-02-05/14-Neslihan/stringmethods.js
2023-02-05/odev.md

14-Neslihan-05.02 odev

---

2023-02-05/18-Tuba Neda/index.html
2023-02-05/18-Tuba Neda/sorular.js

18-Neda - js ödev 

---

2023-02-05/cozum/index.html
2023-02-05/cozum/odev.js

add 2023-02-05-odev-cozum

---

2023-02-19/odev/index1.js
2023-02-19/odev/index2.js
2023-02-19/odev/index3.js

add 2023-02-19 odev

---

2023-02-05/19-Ümit/index.html
2023-02-05/19-Ümit/ödev.js

19-ümit-js ödev

---

2023-02-05/20-Y.Emre/app.js
2023-02-05/20-Y.Emre/index.html

arrays methods

---

2023-02-19/odev/02-Furkan/index.html
2023-02-19/odev/02-Furkan/script.js

05- Furkan - JavaScript Arrays

---

2023-02-19/17-Sıla/ödev.html
2023-02-19/17-Sıla/ödev.js

add first changes

---

2023-02-19/cozum/index.html
2023-02-19/cozum/index1.js
2023-02-19/cozum/index2.js
2023-02-19/cozum/index3.js

add odev cozum

---

2023-02-05/06-Hasan/index.html
2023-02-05/06-Hasan/thirdWoche.js

06-Hasan - js String Arrays ödev

---

2023-02-19/17-Sıla/ödev.js

17.sila.kizil

---

2023-02-26/odev/02-Ali/await.js
2023-02-26/odev/02-Ali/callback.js
2023-02-26/odev/02-Ali/promise.js

02-Ali - AsyncHomeWork

---

2023-02-26/odev/14-Neslihan/index.html
2023-02-26/odev/14-Neslihan/promise.js

14-Neslihan /promise

---

2023-02-26/18-Tuba Neda/async-await.js
2023-02-26/18-Tuba Neda/callback.js
2023-02-26/18-Tuba Neda/index.html
2023-02-26/18-Tuba Neda/promise.js

18-Neda - callback/promise/async-await ödev

---

2023-02-19/19-Ümit/index.html
2023-02-19/19-Ümit/index1.js
2023-02-19/19-Ümit/index2.js
2023-02-19/19-Ümit/index3.js

19-Ümit - js ödev

---

2023-02-26/19-Ümit/await.js
2023-02-26/19-Ümit/callback.js
2023-02-26/19-Ümit/promise.js

19-Ümit- js ödev

---

2023-02-05/20-Y.Emre/README.md
2023-02-05/20-Y.Emre/app.js
2023-02-05/20-Y.Emre/index.html

lasthomework update

---

2023-02-26/odev/11-Muhammet/corba.js
2023-02-26/odev/11-Muhammet/ındex.html

callback ödevi

---

2023-02-26/05-Furkan/index.html
2023-02-26/05-Furkan/script.js

5-Furkan  -Callback, asnyc, await odev

---

2023-03-05/10-Mehmetalp/async-await.html
2023-03-05/10-Mehmetalp/callback-function.html
2023-03-05/10-Mehmetalp/promise.html

10-Mehmetalp-cb-promise-asyncawait

---

2023-02-19/21-Yusuf/index.html
2023-02-19/21-Yusuf/index1.js
2023-02-19/21-Yusuf/index2.js
2023-02-19/21-Yusuf/index3.js

21-Yusuf-JS-High-Array Methods-Homework

---

2023-02-26/21-Yusuf/async-await.js
2023-02-26/21-Yusuf/callback.js
2023-02-26/21-Yusuf/index.html
2023-02-26/21-Yusuf/promise.js

21-Yusuf-JS-Callback-Promise-Async-Await-Homework

---

2023-03-05/21-Yusuf/fetch.js
2023-03-05/21-Yusuf/index.html

21-Yusuf-JS-Fetch-Homework

---

2023-03-12/odev-1.md
2023-03-12/odev-2.md

00-Murat - oop odevleri

---

2023-02-26/odev/15-salih/index.html
2023-02-26/odev/15-salih/index.js

15 salih 02 26

---

2023-03-12/05-Furkan/README.md
2023-03-12/05-Furkan/index.html
2023-03-12/05-Furkan/kronometre.js
2023-03-12/05-Furkan/ucgen.js

05-Furkan JavaScript OOP Projects Odev

---

2023-02-26/06-Hasan/await.js
2023-02-26/06-Hasan/callback.js
2023-02-26/06-Hasan/index.html
2023-02-26/06-Hasan/promise.js

06-Hasan-JS Callback

---

2023-03-12/03-busra/indexucgen.html
2023-03-12/03-busra/odevucgen.js

ucgen alani

---

2023-03-12/15-Salih/index.html
2023-03-12/15-Salih/stopwatch.js
2023-03-12/15-Salih/ucgen.js

15 salih 05 03

---

2023-02-05/14-Neslihan/stringmethods.js

odev cozumunden sonra yapamadigim kisimlari tekrar duzenledim.

14-neslihan 05.02.23

---

2023-03-19/odev_cozum/index.html

add 2023-03-19-odev cozum

---

2023-03-26/odev.md

26.03.2023

---

2023-03-26/05-Furkan/index.html
2023-03-26/05-Furkan/script.js

05-Furkan Todo app 

---

2023-03-12/20-Y.Emre/README.md
2023-03-12/20-Y.Emre/cevre-alan.js
2023-03-12/20-Y.Emre/index.html
2023-03-12/20-Y.Emre/kronometre.js
2023-03-26/05-Furkan/.vscode/settings.json

js oop project

---

2023-03-12/12-Mustafa/index.html
2023-03-12/12-Mustafa/kronometre.js
2023-03-12/12-Mustafa/ucgen.js
2023-03-19/12-mustafa/dom.js
2023-03-19/12-mustafa/index.html

12- mustafa--

---

2023-03-19/Y.Emre/app.js
2023-03-19/Y.Emre/index.html

js form add met DOM

---

2023-03-26/20-Y.emre/app.js
2023-03-26/20-Y.emre/index.html

js todo app using api

---

2023-01-08/18-Tuba Neda/index.html
2023-01-08/18-Tuba Neda/style.css
2023-02-19/18-Tuba Neda/app1.js
2023-02-19/18-Tuba Neda/app2.js
2023-02-19/18-Tuba Neda/app3.js
2023-02-19/18-Tuba Neda/index.html
2023-03-05/18-Tuba Neda/app.js
2023-03-05/18-Tuba Neda/index.html
2023-03-12/18-Tuba Neda/ödev.js
2023-03-19/18-Neda/index.html
2023-03-26/18-Tuba Neda/app.js
2023-03-26/18-Tuba Neda/index.html

- [+] Pull request basligi, '00-Alex - html ödev' seklinde düzenlendi
- [+] Tüm degisiklikler yapildi ve Pull Request review icin hazir

18-TubaNeda- missing homeworks 

---

2023-01-29/10-mehmetalp/appswitch.js
2023-01-29/10-mehmetalp/indexswitch.html

done_290123 HW

---

2023-02-05/10-mehmetalp/odev0502.html
2023-02-05/10-mehmetalp/odev0502.js

Mehmetalp050223

---

2023-03-26/02-Ali/app.js
2023-03-26/02-Ali/index.html

02-Ali - TodoList Homework

---

2023-03-12/14-Neslihan/index.html
2023-03-12/14-Neslihan/stopwatch.js
2023-03-12/14-Neslihan/triangle.js

14-Neslihan-Stopwatch/triangle

---

2023-03-05/01-Ahmet/jss6_5_fetch.js
2023-03-05/01-Ahmet/main.html
2023-03-19/01-Ahmet/jss8_DOM_1.html

01-Ahmet 03-05 ve 03-19

---

2023-03-19/14-neslihan/index.html

14-Neslihan -19.03.2023 odev

---

2023-02-05/09-Kenan/app.js
2023-02-05/09-Kenan/index.html

09-Kenan-Homework-05.02.23

---

2023-03-05/10-Mehmetalp/jsonplaceholder.html
2023-03-05/10-Mehmetalp/jsonplaceholder.js

done 10-Mehmetalp230305 jsonplaceholder

---

2023-03-19/10-mehmetalp/dom-HW.html
2023-03-19/10-mehmetalp/dom-HW.js

10 mehmetalp230319

---

2023-03-12/10-mehmetalp/OOKrometre.js
2023-03-12/10-mehmetalp/OOKronometre.html
2023-03-12/10-mehmetalp/OOucgen.html
2023-03-12/10-mehmetalp/OOucgen.js

 10-Mehmetalp_230312 _kronometre

---

2023-02-26/10-Mehmetalp/async-await.html
2023-02-26/10-Mehmetalp/callback-function.html
2023-02-26/10-Mehmetalp/promise.html

- [ x] Pull request basligi, '00-Alex - html ödev' seklinde düzenlendi
- [x ] Tüm degisiklikler yapildi ve Pull Request review icin hazir

10-mehmetalp230226

---

2023-02-19/10-mehmetalp/mehmetalp-JSHW-index-1.html
2023-02-19/10-mehmetalp/mehmetalp-JSHW-index-1.js
2023-02-19/10-mehmetalp/mehmetalp-JSHW-index-2.html
2023-02-19/10-mehmetalp/mehmetalp-JSHW-index-2.js
2023-02-19/10-mehmetalp/mehmetalp-JSHW-index-3.html
2023-02-19/10-mehmetalp/mehmetalp-JSHW-index-3.js

- [ x] Pull request basligi, '00-Alex - html ödev' seklinde düzenlendi

10 mehmetalp230219

---

2023-03-19/21-Yusuf/custom-fields.html

21-Yusuf-Custom-Fields-Homework

---

2023-03-12/21-Yusuf/chronometer.js
2023-03-12/21-Yusuf/index.html
2023-03-12/21-Yusuf/triangle.js

21-Yusuf-OOP-Triangle-Chronometer-Homework

---

2023-03-12/02-Ali/index.html
2023-03-19 2/02-Ali/index.html

02-Ali- DOM Homework

---

2023-02-19/09-Kenan/app1.js
2023-02-19/09-Kenan/app2.js
2023-02-19/09-Kenan/app3.js
2023-02-19/09-Kenan/index1.html
2023-02-19/09-Kenan/index2.html
2023-02-19/09-Kenan/index3.html

09-KenanHomework-19.02.23

---

2023-04-16/odev-1.md
2023-04-16/odev-2.md
2023-04-16/odev-2/app.js

import-export odev

---

2023-04-16/05-Furkan/odev-1/app.js
2023-04-16/05-Furkan/odev-1/nokta.js
2023-04-16/05-Furkan/odev-1/package-lock.json
2023-04-16/05-Furkan/odev-1/package.json
2023-04-16/05-Furkan/odev-1/ucgen.js
2023-04-16/05-Furkan/odev-2/GetPriceAPI.js
2023-04-16/05-Furkan/odev-2/app.js
2023-04-16/05-Furkan/odev-2/package-lock.json
2023-04-16/05-Furkan/odev-2/package.json
2023-04-16/05-Furkan/odev-2/productList.js
2023-04-16/05-Furkan/odev-2/proxy.js

05-Furkan - supermarket app and export/import

---

2023-05-01/05-Furkan/app.js
2023-05-01/05-Furkan/calc.js
2023-05-01/05-Furkan/package-lock.json
2023-05-01/05-Furkan/package.json

05-Furkan - Calculate -Get -Post Process

---

2023-04-16/06-Hasan/1.  ödev/app.js
2023-04-16/06-Hasan/1.  ödev/nokta.js
2023-04-16/06-Hasan/1.  ödev/package.json
2023-04-16/06-Hasan/1.  ödev/ucgen.js
2023-04-16/06-Hasan/2. ödev/GetPriceAPI.js
2023-04-16/06-Hasan/2. ödev/app.js
2023-04-16/06-Hasan/2. ödev/package.json
2023-04-16/06-Hasan/2. ödev/proxy.js
2023-04-16/06-Hasan/2. ödev/urunListesi.js

06 -hasan- Market uygulaması (Node-ödev) 

---

2023-05-15/05-Furkan/.gitattributes
2023-05-15/05-Furkan/package-lock.json
2023-05-15/05-Furkan/package.json
2023-05-15/05-Furkan/src/app.js
2023-05-15/05-Furkan/src/middlewares/auht.js
2023-05-15/05-Furkan/src/middlewares/logger.js
2023-05-15/05-Furkan/src/models/Todos.js
2023-05-15/05-Furkan/src/models/Userss.js
2023-05-15/05-Furkan/src/routes/todosRouter.js
2023-05-15/05-Furkan/src/routes/usersRoutes.js
2023-05-15/05-Furkan/src/services/todoServices.js
2023-05-15/05-Furkan/src/services/usersService.js
2023-05-15/05-Furkan/src/utils/hash.js

05-Furkan - Created server with Nodejs Odev

---

.gitignore
2023-04-16/21-Y.Emre/ödev-1/app.js
2023-04-16/21-Y.Emre/ödev-1/nokta.js
2023-04-16/21-Y.Emre/ödev-1/package-lock.json
2023-04-16/21-Y.Emre/ödev-1/package.json
2023-04-16/21-Y.Emre/ödev-1/ucgen.js
2023-04-16/21-Y.Emre/ödev-2/.gitignore
2023-04-16/21-Y.Emre/ödev-2/app.js
2023-04-16/21-Y.Emre/ödev-2/package-lock.json
2023-04-16/21-Y.Emre/ödev-2/package.json
2023-04-16/21-Y.Emre/ödev-2/src/getPriceAPI.js
2023-04-16/21-Y.Emre/ödev-2/src/productList.js
2023-04-16/21-Y.Emre/ödev-2/src/proxy.js

supermarket app and export/import

---

2023-04-16/10-MehmetAlp/ODEV-1/app.js
2023-04-16/10-MehmetAlp/ODEV-1/nokta.js
2023-04-16/10-MehmetAlp/ODEV-1/package.json
2023-04-16/10-MehmetAlp/ODEV-1/ücgen.js
2023-04-16/10-MehmetAlp/ODEV-2/app.js
2023-04-16/10-MehmetAlp/ODEV-2/getPriceAPI.js
2023-04-16/10-MehmetAlp/ODEV-2/package.json
2023-04-16/10-MehmetAlp/ODEV-2/proxy.js
2023-04-16/10-MehmetAlp/ODEV-2/ürünListesi.js

- [ x] Pull request basligi, '00-Alex - html ödev' seklinde düzenlendi

HW-1 and HW-2 moduler yapi

---

2023-05-01/10-MehmetAlp/.gitignore
2023-05-01/10-MehmetAlp/app.js
2023-05-01/10-MehmetAlp/calc.js
2023-05-01/10-MehmetAlp/package-lock.json
2023-05-01/10-MehmetAlp/package.json

10-MehmetAp 23-05-01 calcjs-done

---

.vscode/settings.json

.vcode sorunu
